//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikel()
        {
            this.bestellposition = new HashSet<Bestellposition>();
            this.kundenpreis = new HashSet<Kundenpreis>();
            this.lagerbuchung = new HashSet<Lagerbuchung>();
            this.lagerposition = new HashSet<Lagerposition>();
        }
    
        public int Id { get; set; }
        public string Artikelnr { get; set; }
        public string Bezeichnung { get; set; }
        public decimal Ep { get; set; }
        public decimal Bruttovp { get; set; }
        public Nullable<int> FkArtikelMwstsatz { get; set; }
        public System.Guid SsmaRowid { get; set; }
    
        public virtual Mwstsatz mwstsatz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellposition> bestellposition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kundenpreis> kundenpreis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lagerbuchung> lagerbuchung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lagerposition> lagerposition { get; set; }
    }
}
