//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public artikel()
        {
            this.bestellposition = new HashSet<bestellposition>();
            this.kundenpreis = new HashSet<kundenpreis>();
            this.lagerbuchung = new HashSet<lagerbuchung>();
            this.lagerposition = new HashSet<lagerposition>();
        }
    
        public int Id { get; set; }
        public string Artikelnr { get; set; }
        public string Bezeichnung { get; set; }
        public decimal Ep { get; set; }
        public decimal Bruttovp { get; set; }
        public Nullable<int> FkArtikelMwstsatz { get; set; }
        public System.Guid SsmaRowid { get; set; }
    
        public virtual mwstsatz mwstsatz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bestellposition> bestellposition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kundenpreis> kundenpreis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lagerbuchung> lagerbuchung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lagerposition> lagerposition { get; set; }
    }
}
