//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int Id { get; set; }
        public string ModQuery { get; set; }
        public string ModTable { get; set; }
        public string ModKind { get; set; }
        public string ModUser { get; set; }
        public System.DateTime ModTime { get; set; }
    }
}
