//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellposition
    {
        public int Id { get; set; }
        public int FkBestellpositionArtikel { get; set; }
        public decimal Menge { get; set; }
        public int FkBestellpositionLagerposition { get; set; }
        public Nullable<int> FkBestellpositionKundenpreis { get; set; }
        public string Notiz { get; set; }
        public Nullable<int> FkBestellpositionBestellung { get; set; }
    
        public virtual Artikel artikel { get; set; }
        public virtual Bestellung bestellung { get; set; }
        public virtual Kundenpreis kundenpreis { get; set; }
        public virtual Lagerposition lagerposition { get; set; }
    }
}
