//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bestellposition
    {
        public int Id { get; set; }
        public int fk_Bestellposition_Artikel { get; set; }
        public decimal Menge { get; set; }
        public int fk_Bestellposition_LagerPosition { get; set; }
        public Nullable<int> fk_Bestellposition_KundenPreis { get; set; }
        public string Notiz { get; set; }
        public Nullable<int> fk_Bestellposition_Bestellung { get; set; }
    
        public virtual artikel artikel { get; set; }
        public virtual bestellung bestellung { get; set; }
        public virtual kundenpreis kundenpreis { get; set; }
        public virtual lagerposition lagerposition { get; set; }
    }
}
