//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpContext : DbContext
    {
        public ErpContext()
            : base("name=ErpContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abteilung> Abteilung { get; set; }
        public virtual DbSet<Adresse> Adresse { get; set; }
        public virtual DbSet<Artikel> Artikel { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<Bestellposition> Bestellposition { get; set; }
        public virtual DbSet<Bestellung> Bestellung { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
        public virtual DbSet<Kundenpreis> Kundenpreis { get; set; }
        public virtual DbSet<Lager> Lager { get; set; }
        public virtual DbSet<Lagerbuchung> Lagerbuchung { get; set; }
        public virtual DbSet<Lagerposition> Lagerposition { get; set; }
        public virtual DbSet<Land> Land { get; set; }
        public virtual DbSet<Lieferschein> Lieferschein { get; set; }
        public virtual DbSet<Lohnabrechnung> Lohnabrechnung { get; set; }
        public virtual DbSet<Mitarbeiter> Mitarbeiter { get; set; }
        public virtual DbSet<Mwstsatz> Mwstsatz { get; set; }
        public virtual DbSet<Ort> Ort { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Rechnung> Rechnung { get; set; }
        public virtual DbSet<Strasse> Strasse { get; set; }
        public virtual DbSet<Zahlung> Zahlung { get; set; }
    }
}
