//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpContext : DbContext
    {
        public ErpContext()
            : base("name=ErpContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abteilung> Abteilungen { get; set; }
        public virtual DbSet<Adresse> Adressen { get; set; }
        public virtual DbSet<Artikel> Artikel { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<Bestellposition> Bestellpositionen { get; set; }
        public virtual DbSet<Bestellung> Bestellungen { get; set; }
        public virtual DbSet<Kunde> Kunden { get; set; }
        public virtual DbSet<Kundenpreis> Kundenpreise { get; set; }
        public virtual DbSet<Lager> Lager { get; set; }
        public virtual DbSet<Lagerbuchung> Lagerbuchungen { get; set; }
        public virtual DbSet<Lagerposition> Lagerpositionen { get; set; }
        public virtual DbSet<Land> Laender { get; set; }
        public virtual DbSet<Lieferschein> Lieferscheine { get; set; }
        public virtual DbSet<Lohnabrechnung> Lohnabrechnungen { get; set; }
        public virtual DbSet<Mitarbeiter> Mitarbeiter { get; set; }
        public virtual DbSet<Mwstsatz> Mwstsaetze { get; set; }
        public virtual DbSet<Ort> Orte { get; set; }
        public virtual DbSet<Person> Personen { get; set; }
        public virtual DbSet<Rechnung> Rechnungen { get; set; }
        public virtual DbSet<Strasse> Strassen { get; set; }
        public virtual DbSet<Zahlung> Zahlungen { get; set; }
    }
}
