//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class kundenpreis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kundenpreis()
        {
            this.bestellposition = new HashSet<bestellposition>();
        }
    
        public int Id { get; set; }
        public int fk_KundenPreis_Artikel { get; set; }
        public int fk_KundenPreis_Kunde { get; set; }
        public decimal Verkaufspreis { get; set; }
        public Nullable<System.DateTime> GueltigBis { get; set; }
        public string Waehrung { get; set; }
        public Nullable<int> Rabatt { get; set; }
    
        public virtual artikel artikel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bestellposition> bestellposition { get; set; }
        public virtual kunde kunde { get; set; }
    }
}
