//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lagerposition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lagerposition()
        {
            this.bestellposition = new HashSet<bestellposition>();
            this.lagerbuchung = new HashSet<lagerbuchung>();
        }
    
        public int Id { get; set; }
        public int fk_LagerPosition_Artikel { get; set; }
        public int fk_LagerPosition_Lager { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public decimal MinMenge { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        public virtual artikel artikel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bestellposition> bestellposition { get; set; }
        public virtual lager lager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lagerbuchung> lagerbuchung { get; set; }
    }
}
