//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lagerposition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lagerposition()
        {
            this.Bestellposition = new HashSet<Bestellposition>();
            this.Lagerbuchung = new HashSet<Lagerbuchung>();
        }
    
        public int Id { get; set; }
        public int FkLagerpositionArtikel { get; set; }
        public int FkLagerpositionLager { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public decimal Minmenge { get; set; }
        public System.Guid SsmaRowid { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellposition> Bestellposition { get; set; }
        public virtual Lager Lager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lagerbuchung> Lagerbuchung { get; set; }
    }
}
