//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lagerbuchung
    {
        public int Id { get; set; }
        public decimal Menge { get; set; }
        public System.DateTime Buchungsdatum { get; set; }
        public int FkLagerbuchungLagerposition { get; set; }
        public int FkLagerbuchungArtikel { get; set; }
    
        public virtual artikel artikel { get; set; }
        public virtual lagerposition lagerposition { get; set; }
    }
}
