//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lieferschein
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lieferschein()
        {
            this.lieferschein1 = new HashSet<Lieferschein>();
        }
    
        public int Id { get; set; }
        public System.DateTime Lieferdatum { get; set; }
        public Nullable<int> FkLieferscheinRechnung { get; set; }
        public Nullable<int> FkLieferscheinLieferschein { get; set; }
        public int FkLieferscheinBestellung { get; set; }
        public int FkLieferscheinAdresse { get; set; }
    
        public virtual Adresse adresse { get; set; }
        public virtual Bestellung bestellung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lieferschein> lieferschein1 { get; set; }
        public virtual Lieferschein lieferschein2 { get; set; }
        public virtual Rechnung rechnung { get; set; }
    }
}
