//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lohnabrechnung
    {
        public int Id { get; set; }
        public int fk_Lohnabrechnung_Mitarbeiter { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<decimal> SollStunden { get; set; }
        public Nullable<decimal> IstStunden { get; set; }
        public Nullable<decimal> FerienBezug { get; set; }
        public Nullable<decimal> KrankheitStunden { get; set; }
        public Nullable<decimal> UnbezahltStunden { get; set; }
        public Nullable<decimal> EOErsatzberechtigteStunden { get; set; }
        public decimal Stundenlohn { get; set; }
        public System.Guid ssma_rowid { get; set; }
    
        public virtual mitarbeiter mitarbeiter { get; set; }
    }
}
