//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBW.BPFM.DBAdv.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahlung
    {
        public int Id { get; set; }
        public int FkZahlungKunde { get; set; }
        public int FkZahlungRechnung { get; set; }
        public decimal Betrag { get; set; }
    
        public virtual Kunde Kunde { get; set; }
        public virtual Rechnung Rechnung { get; set; }
    }
}
